name: fcm_playground
description: "A tool to test Firebase Cloud Messaging (FCM) notifications on supported devices."
publish_to: 'none'
version: 1.0.0+1
repository: https://github.com/AngeloAvv/fcm_playground
issue_tracker: https://github.com/AngeloAvv/fcm_playground/issues
homepage: https://www.angelocassano.it

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_route: ^9.0.0
  collection: ^1.19.1
  dart_mapper: ^0.8.0
  drift: ^2.26.0
  drift_flutter: ^0.2.4
  file_picker: ^10.1.2
  flutter_bloc: ^9.0.0
  flutter_essentials_kit: ^2.5.0
  flutter_launch_arguments: ^1.0.1
  freezed_annotation: ^3.0.0
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  http: ^1.3.0
  intl: any
  pine: ^1.0.3
  provider: ^6.1.2
  reactive_forms: ^17.0.1
  rxdart: ^0.28.0
  shared_preferences: ^2.5.3
  talker: ^4.6.13
  flutter_staggered_grid_view: ^0.7.0
  json_text_field:
    git: https://github.com/antonioCaballero17/json_text_field.git
  settings_ui: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: 7.3.0 #TODO: https://github.com/dart-lang/mockito/issues/810
  auto_route_generator: ^9.3.1
  bloc_test: ^10.0.0
  build_runner: ^2.4.9
  dart_mapper_generator: ^0.8.0
  data_fixture_dart: ^2.2.0
  drift_dev: ^2.26.0
  flutter_lints: ^5.0.0
  freezed: ^3.0.0
  mockito: ^5.4.4
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
